### ISSUE TITLE
Installing pyrocms-theme breaks pyrocms completely

### ISSUE THREAD

**Issue by andreasotto** [websemantics/pyrocms-theme#6] opened 2016-12-05 13:25 UTC
If you do a clean fresh install with just:

`composer create-project pyrocms/pyrocms`

everything is OK, until you add pyrocms-theme with:

`composer require websemantics/pyrocms-theme`

the pyrocms installation is broken and returns HTTP ERROR 500 on every page.

The log says:

```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'No hint path defined for [streams].' in /var/www/pyrocms.dev/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112\nStack trace:\n#0 /var/www/pyrocms.dev/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\\View\\FileViewFinder->getNamespaceSegments('streams::errors...')\n#1 /var/www/pyrocms.dev/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\\View\\FileViewFinder->findNamedPathView('streams::errors...')\n#2 /var/www/pyrocms.dev/pyrocms/vendor/laravel/framework/src/Illuminate/View/Factory.php(174): Illuminate\\View\\FileViewFinder->find('streams::errors...')\n#3 /var/www/pyrocms.dev/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('streams::errors...', Array)\n#4 /var/www/pyrocms.dev/pyrocms/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(69): Illuminate\\Routing\\ResponseFactory->view('s in /var/www/pyrocms.dev/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 112
```

What is going on?

**Comment by websemantics** [comment] 2016-12-05 14:34
@andreasotto thanks for the heads up, I'll check if there has been breaking changes in pyro, stay tuned,

**Comment by websemantics** [comment] 2016-12-06 16:13
Just installed the theme and it worked! This seem to happen only when you have the theme installed prior to installing Pyro, which is what I am going to test shortly,

**Comment by bloveless** [comment] 2016-12-06 16:58
I was having a similar issue. I was able to install the theme and get it working locally, but when I pushed it to my production server... all hell broke loose!

Also the streams hint path error hides the actual error. It should be the error right above that error. @andreasotto will you get into your log again and look for an error right before that streams hint error. I wonder if it is the same error that I was seeing in the variables.php file.

```
[2016-11-25 02:29:28] production.ERROR: ErrorException: Undefined index:  in /home/boulderingwall/pyro/core/websemantics/pyrocms-theme/resources/config/variables.php:34
Stack trace:
#0 /home/boulderingwall/pyro/core/websemantics/pyrocms-theme/resources/config/variables.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/boulderin...', 34, Array)
#1 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(84): require('/home/boulderin...')
#2 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Support/Configurator.php(62): Illuminate\Filesystem\Filesystem->getRequire('/home/boulderin...')
#3 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Addon/AddonIntegrator.php(154): Anomaly\Streams\Platform\Support\Configurator->addNamespace('websemantics.th...', '/home/boulderin...')
#4 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Addon/AddonManager.php(121): Anomaly\Streams\Platform\Addon\AddonIntegrator->register('/home/boulderin...', Array, Array)
#5 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/StreamsServiceProvider.php(271): Anomaly\Streams\Platform\Addon\AddonManager->register()
#6 [internal function]: Anomaly\Streams\Platform\StreamsServiceProvider->Anomaly\Streams\Platform\{closure}(Object(Illuminate\Foundation\Application))
#7 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(808): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#8 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#9 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(113): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /home/boulderingwall/pyro/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2016-11-25 02:29:31] production.ERROR: ErrorException: Undefined index:  in /home/boulderingwall/pyro/core/websemantics/pyrocms-theme/resources/config/variables.php:34
Stack trace:
#0 /home/boulderingwall/pyro/core/websemantics/pyrocms-theme/resources/config/variables.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/boulderin...', 34, Array)
#1 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(84): require('/home/boulderin...')
#2 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Support/Configurator.php(62): Illuminate\Filesystem\Filesystem->getRequire('/home/boulderin...')
#3 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Addon/AddonIntegrator.php(154): Anomaly\Streams\Platform\Support\Configurator->addNamespace('websemantics.th...', '/home/boulderin...')
#4 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Addon/AddonManager.php(121): Anomaly\Streams\Platform\Addon\AddonIntegrator->register('/home/boulderin...', Array, Array)
#5 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/StreamsServiceProvider.php(271): Anomaly\Streams\Platform\Addon\AddonManager->register()
#6 [internal function]: Anomaly\Streams\Platform\StreamsServiceProvider->Anomaly\Streams\Platform\{closure}(Object(Illuminate\Foundation\Application))
#7 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(808): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#8 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#9 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(254): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Foundation\Http\Kernel->bootstrap()
#13 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#14 /home/boulderingwall/pyro/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#15 {main}  
[2016-11-25 02:29:31] production.ERROR: InvalidArgumentException: No hint path defined for [streams]. in /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112
Stack trace:
#0 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\View\FileViewFinder->getNamespaceSegments('streams::errors...')
#1 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamedPathView('streams::errors...')
#2 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/View/Factory.php(174): Illuminate\View\FileViewFinder->find('streams::errors...')
#3 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\View\Factory->make('streams::errors...', Array)
#4 /home/boulderingwall/pyro/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(69): Illuminate\Routing\ResponseFactory->view('streams::errors...', Array, 500)
#5 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(313): Anomaly\Streams\Platform\Exception\ExceptionHandler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#6 /home/boulderingwall/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(121): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(ErrorException))
#7 /home/boulderingwall/pyro/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#8 {main}  
```

**Comment by bloveless** [comment] 2016-12-06 17:03
One more note I was trying to install the theme on a preexisting website that had been deployed for a little while.

**Comment by websemantics** [comment] 2016-12-06 17:08
Oh gracious, `variables.php` is still there, that's a disaster, hh. Removing that would definitely improve the situation, hopefully resolve it, will see. Thanks @bloveless for detailed error log,

**Comment by bloveless** [comment] 2016-12-06 17:15
Not a problem! I should have said something earlier since I really want to use this theme on a project that I've been working on!

**Comment by websemantics** [comment] 2016-12-06 23:27
When in doubt, open an issue :)

**Comment by websemantics** [comment] 2016-12-07 01:33
Wasn't able to reproduce the error, arrah! 

But, I removed `variables.php` which I believe is the culprit. 

Let me know if that didn't fix it. Otherwise I will close this issue shortly!

**Comment by bloveless** [comment] 2016-12-07 05:56
In my scenario it fixed it. I LOVE THIS THEME! And the theme chooser in settings is just amazing! Thank you!

**Comment by websemantics** [comment] 2016-12-07 11:56
Super, .. thanks @bloveless, glad you like it. I have many other ideas to improve it once I have some free time.

**Closed as completed by websemantics** 2016-12-07 11:56 UTC
